export default [
  {
    codeType: 1,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 100000,
  },
  {
    codeType: 2,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 100000,
  },
  {
    codeType: 3,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 100000,
  },
  {
    codeType: 4,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 150000,
  },
  {
    codeType: 5,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 150000,
  },
  {
    codeType: 6,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 150000,
  },
  {
    codeType: 7,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 150000,
  },
  {
    codeType: 8,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 200000,
  },
  {
    codeType: 9,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 200000,
  },
  {
    codeType: 10,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 200000,
  },
  {
    codeType: 11,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 200000,
  },
  {
    codeType: 12,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 500000,
  },
  {
    codeType: 13,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 500000,
  },
  {
    codeType: 14,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 500000,
  },
  {
    codeType: 15,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 500000,
  },
  {
    codeType: 16,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 500000,
  },
  {
    codeType: 17,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 500000,
  },
  {
    codeType: 18,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 500000,
  },
  {
    codeType: 19,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 500000,
  },
  {
    codeType: 20,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 500000,
  },
  {
    codeType: 21,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 200000,
  },
  {
    codeType: 22,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 200000,
  },
  {
    codeType: 23,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 200000,
  },
  {
    codeType: 24,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 850000,
  },
  {
    codeType: 25,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 850000,
  },
  {
    codeType: 26,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 850000,
  },
  {
    codeType: 27,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 850000,
  },
  {
    codeType: 28,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 850000,
  },
  {
    codeType: 29,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 850000,
  },
  {
    codeType: 30,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 850000,
  },
  {
    codeType: 31,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 850000,
  },
  {
    codeType: 32,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 850000,
  },
  {
    codeType: 33,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 850000,
  },
  {
    codeType: 34,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 850000,
  },
  {
    codeType: 35,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 850000,
  },
  {
    codeType: 36,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 500000,
  },
  {
    codeType: 37,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 500000,
  },
  {
    codeType: 38,
    "Excess on MD in %": 5.0,
    "Excess on Theft & Fire (Total loss) in %": 2.5,
    "Minimum Excess in RWF": 500000,
  },
];
