export default [
  {
    codeType: 1,
    vehicleUsageCode: 2,
    vehicleUsageLabel: "Private",
    occupant: 0.008,
    seats: null,
  },
  {
    codeType: 2,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: null,
  },
  {
    codeType: 3,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 7500,
  },
  {
    codeType: 4,
    vehicleUsageCode: 2,
    vehicleUsageLabel: "Private",
    occupant: 0.005,
    seats: null,
  },
  {
    codeType: 5,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: null,
  },
  {
    codeType: 6,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 14000,
  },
  {
    codeType: 7,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 7500,
  },
  {
    codeType: 8,
    vehicleUsageCode: 2,
    vehicleUsageLabel: "Private",
    occupant: 0.005,
    seats: null,
  },
  {
    codeType: 9,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: null,
  },
  {
    codeType: 10,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 14000,
  },
  {
    codeType: 11,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 7500,
  },
  {
    codeType: 12,
    vehicleUsageCode: 2,
    vehicleUsageLabel: "Private",
    occupant: 0.005,
    seats: null,
  },
  {
    codeType: 13,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: null,
  },
  {
    codeType: 14,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 14000,
  },
  {
    codeType: 15,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 7500,
  },
  {
    codeType: 16,
    vehicleUsageCode: 2,
    vehicleUsageLabel: "Private",
    occupant: 0.005,
    seats: null,
  },
  {
    codeType: 17,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: null,
  },
  {
    codeType: 18,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 14000,
  },
  {
    codeType: 19,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 7500,
  },
  {
    codeType: 20,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: null,
  },
  {
    codeType: 21,
    vehicleUsageCode: 2,
    vehicleUsageLabel: "Private",
    occupant: 0.005,
    seats: null,
  },
  {
    codeType: 22,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 14000,
  },
  {
    codeType: 23,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 7500,
  },
  {
    codeType: 24,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 7500,
  },
  {
    codeType: 25,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 7500,
  },
  {
    codeType: 26,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 7500,
  },
  {
    codeType: 27,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 7500,
  },
  {
    codeType: 28,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 7500,
  },
  {
    codeType: 29,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 7500,
  },
  {
    codeType: 30,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 7500,
  },
  {
    codeType: 31,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 7500,
  },
  {
    codeType: 32,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 7500,
  },
  {
    codeType: 33,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 7500,
  },
  {
    codeType: 34,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 7500,
  },
  {
    codeType: 35,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 7500,
  },
  {
    codeType: 36,
    vehicleUsageCode: 2,
    vehicleUsageLabel: "Private",
    occupant: 0.005,
    seats: null,
  },
  {
    codeType: 37,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 7500,
  },
  {
    codeType: 38,
    vehicleUsageCode: 1,
    vehicleUsageLabel: "Commercial",
    occupant: 0.01,
    seats: 7500,
  },
];